spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teachingsystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#server:
#  port: 9999:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.oaec.teachingsystem.domain
